version: "3.9"

services:
  backend:
    build:
      context: backend/app-python/
    restart: always
    ports:
      - 8181:8000
  ml-resume:
    build:
      context: ml/backend/app-python/
    environment:
      - REGION_NAME=ru-central1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: always
    ports:
      - 5000:8000
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
        - "3000:3000"
