version: "3.9"

services:
  backend:
    build:
      context: backend/app-python/
    image: ghcr.io/avalanche05/app-python:${APP_TAG:-local}
    restart: always
    ports:
      - 8181:8000
  frontend:
    image: ghcr.io/avalanche05/t1-frontend:${APP_TAG:-local}
    build:
        context: ./frontend
        dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
        - "3000:3000"
