name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Up docker-compose in VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          BACK_ENV: ${{ secrets.ENV }}
          FRONT_ENV: ${{ secrets.FRONT_ENV }}
          AWS_ACCESS_KEY_ID: 123
          AWS_SECRET_ACCESS_KEY: 123
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: BACK_ENV,FRONT_ENV,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
          script: |
            cd t1
            git fetch origin
            git reset --hard origin/main
            echo "$BACK_ENV" > ./backend/app-python/.env
            echo "$FRONT_ENV" > ./frontend/.env
            set AWS_ACCESS_KEY_ID=123
            set AWS_SECRET_ACCESS_KEY=123
            sudo docker compose up --build -d
