name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }} 
      - uses: actions/checkout@v4
      - name: Build and push the app-python Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/app-python
          push: true
          tags: |
            ghcr.io/avalanche05/app-python:latest
            ghcr.io/avalanche05/app-python:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: http://dino-misis.ru:8443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}