name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Up docker-compose in VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV: ${{ secrets.ENV }}
          FRONT_ENV: ${{ secrets.FRONT_ENV }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd t1
            git pull
            echo "$env" > ./backend/app-python/.env
            echo "$FRONT_ENV" > ./frontend/.env
            sudo docker compose up --build -d
